export const DEMO_TRANSACTIONS = [
  { Action: "Buy", Date: "20/02/2026", Quantity: "530,85 EUR", Company: "TakeTwo (TTWO)",                  Industry: "Entertainment", Bucket: "Wildshot"  },
  { Action: "Buy", Date: "21/02/2026", Quantity: "85,60 EUR",  Company: "TakeTwo (TTWO)",                  Industry: "Entertainment", Bucket: "Wildshot"  },
  { Action: "Buy", Date: "23/02/2026", Quantity: "248,00 EUR", Company: "Constellation Energy Corp (CEG)", Industry: "Energy",        Bucket: "Wildshot"  },
  { Action: "Buy", Date: "01/03/2026", Quantity: "90,00 EUR",  Company: "Vanguard S&P 500 (VOO)",          Industry: "ETF",           Bucket: "Core"      },
  { Action: "Buy", Date: "01/03/2026", Quantity: "80,00 EUR",  Company: "Microsoft (MSFT)",                Industry: "Technology",    Bucket: "Core"      },
  { Action: "Buy", Date: "01/03/2026", Quantity: "125,00 EUR", Company: "NVIDIA (NVDA)",                   Industry: "Technology",    Bucket: "Satellite" },
  { Action: "Buy", Date: "01/03/2026", Quantity: "125,00 EUR", Company: "Vertiv (VRT)",                    Industry: "Industrials",   Bucket: "Satellite" },
];

export const DEMO_HISTORY = [
  { Fecha: "Mar 2026", Valor: 1283 },
  { Fecha: "Abr 2026", Valor: 1750 },
];

export const TUTORIAL_TAB_ORDER = ["proyecto", "evolucion", "distribucion", "candidates", "movimientos", "analisis", "config"];

export const TUTORIAL_STEPS = {
  proyecto: [
    { section: "Pantalla de inicio",    selector: null,
      title: "Bienvenido a STOX",
      text: "Esta es tu pantalla de inicio. Aquí defines los parámetros base de tu estrategia. Todo el dashboard —proyecciones, sugerencias y análisis— se alimenta de lo que configures aquí." },
    { section: "Modo de inversión",     selector: '[data-tut="modo-inversion"]',
      title: "¿Puntual o periódica?",
      text: "El bloque negro de arriba. Elige si invertirás una cantidad total de una sola vez (Puntual) o irás aportando de forma regular (Periódica). Esto cambia cómo se calculan todas las proyecciones." },
    { section: "Importe",               selector: '[data-tut="importe"]',
      title: "Tu capital de inversión",
      text: "El panel de la izquierda. Introduce el capital que destinas a esta estrategia. Si es periódica, indica cuánto aportas cada mes o trimestre. El dashboard derivará la inversión anual total automáticamente." },
    { section: "Análisis con Claude",   selector: '[data-tut="claude-analysis"]',
      title: "Informes con IA",
      text: "El bloque oscuro con el logotipo de Claude. Escribe un evento geopolítico o de mercado y genera un informe en profundidad. El análisis revisa tu portfolio y busca nuevas oportunidades relacionadas." },
    { section: "Split deseado",         selector: '[data-tut="split"]',
      title: "Distribución por bucket",
      text: "El panel con los tres sliders. Define qué porcentaje de tu capital va a Core (estable), Satellite (crecimiento) y Wildshots (especulativo). Deben sumar 100%. Usa los presets como punto de partida." },
    { section: "Retorno y horizonte",   selector: '[data-tut="importe"]',
      title: "Proyección a futuro",
      text: "El panel de la derecha. Fija tu retorno anual objetivo y el número de años. El dashboard calculará a cuánto llegaría tu capital al final del plazo con esos parámetros." },
  ],
  evolucion: [
    { section: "Inversión vs objetivo", selector: '[data-tut="evo-inversion"]',
      title: "¿Cómo vas respecto al plan?",
      text: "El panel de la izquierda. Compara lo que llevas invertido con tu objetivo anual o puntual. La barra de progreso te indica el porcentaje alcanzado de tu meta." },
    { section: "Retorno potencial",     selector: '[data-tut="evo-retorno"]',
      title: "Cuánto puede crecer tu cartera",
      text: "El panel verde. Muestra el retorno esperado ponderado según el campo 'potencial' de tu analysis.json. Solo se calcula para posiciones que tengan ese dato cubierto." },
    { section: "Proyección histórica",  selector: '[data-tut="evo-grafico"]',
      title: "El gráfico de evolución",
      text: "La línea sólida negra es lo que has invertido históricamente. La línea dorada muestra el capital acumulado planificado y la azul punteada es la proyección aplicando el retorno esperado." },
  ],
  distribucion: [
    { section: "Métricas clave",        selector: '[data-tut="portfolio-metricas"]',
      title: "Resumen del portfolio",
      text: "Las tres tarjetas superiores. De izquierda a derecha: capital total invertido, ratio riesgo/recompensa promedio de la cartera (R/R) y retorno potencial total en euros." },
    { section: "Distribución real vs objetivo", selector: '[data-tut="portfolio-split"]',
      title: "¿Estás en el split correcto?",
      text: "Las barras de cada bucket. Comparan el peso real de cada tipo de activo en tu cartera con el objetivo que fijaste en Inicio. Las barras rojas indican desviación respecto al plan." },
    { section: "Posiciones actuales",   selector: '[data-tut="portfolio-split"]',
      title: "Detalle de cada posición",
      text: "La tabla de abajo lista todas tus posiciones con su bucket, importe invertido, peso en la cartera y datos de análisis si los hay. Puedes expandir cada una para ver la tesis." },
  ],
  candidates: [
    { section: "Lista de candidatos",   selector: '[data-tut="candidates-header"]',
      title: "Empresas bajo seguimiento",
      text: "Todos los tickers de tu analysis.json aparecen aquí agrupados por bucket. Muestra la tesis de inversión, la ventaja competitiva y el rango de precios esperado." },
    { section: "Rango de precios",      selector: '[data-tut="candidates-header"]',
      title: "Bajada máxima y subida máxima",
      text: "El badge rojo/verde en cada candidato. Viene del campo 'rango' de tu JSON y refleja el escenario bajista y alcista estimado. El ratio R/R resume la asimetría riesgo/recompensa." },
    { section: "Tesis de inversión",    selector: '[data-tut="candidates-header"]',
      title: "Despliega para leer más",
      text: "Haz clic en cualquier empresa para expandir su ficha completa: descripción del negocio, ventaja competitiva, motivo de inversión, estimaciones y escenarios." },
  ],
  movimientos: [
    { section: "Next Move",             selector: '[data-tut="next-move"]',
      title: "Qué hacer ahora",
      text: "El bloque de cabecera. Resume la acción más urgente según el estado actual de tu cartera: si hay posiciones a rotar, oportunidades de compra claras o si el portfolio está en orden." },
    { section: "Ventas recomendadas",   selector: '[data-tut="mov-ventas"]',
      title: "Posiciones a reconsiderar",
      text: "Posiciones de tu portfolio cuyo R/R es inferior a 1 (la bajada potencial supera la subida) o que tienen marcado 'rotate: true' en el análisis. Aparecen ordenadas de peor a mejor." },
    { section: "Compras recomendadas",  selector: '[data-tut="mov-compras"]',
      title: "Candidatos con mejor R/R",
      text: "Tickers de tu analysis.json que aún no tienes en cartera, ordenados por ratio R/R descendente. Son las entradas con mejor asimetría riesgo/recompensa disponibles." },
    { section: "Todos los candidatos",  selector: '[data-tut="mov-todos"]',
      title: "Vista completa por bucket",
      text: "La sección inferior. Muestra todos los candidatos del análisis agrupados por bucket, con indicador de cuáles ya tienes en cartera. Útil para comparar antes de actuar." },
  ],
  analisis: [
    { section: "Candidatos por bucket", selector: '[data-tut="analisis-buckets"]',
      title: "Análisis agrupado",
      text: "Los candidatos del JSON aparecen agrupados por tipo: Core, Satellite y Wildshots. El badge 'En cartera' (azul) indica qué empresas ya tienes en tu portfolio." },
    { section: "Indicadores por empresa", selector: '[data-tut="analisis-buckets"]',
      title: "R/R, potencial y estimaciones",
      text: "Cada fila muestra el ratio R/R, el upside potencial y las estimaciones de precio. Los colores indican calidad: verde para R/R ≥ 2.5, ámbar para ≥ 1.5 y rojo para < 1.5." },
    { section: "Riesgo del portfolio",  selector: '[data-tut="analisis-riesgo"]',
      title: "Escenarios por bucket",
      text: "La sección inferior muestra la exposición máxima a pérdida de cada bucket según los rangos bajistas de tu análisis. Te ayuda a calibrar cuánto puedes perder en el peor escenario." },
  ],
  config: [
    { section: "Datos de posiciones (CSV)", selector: '[data-tut="config-csv"]',
      title: "Importa tu historial de eToro",
      text: "El panel izquierdo. Arrastra o selecciona el CSV exportado de tu Google Sheets con las operaciones de eToro. La app lo procesa íntegramente en local, sin enviar datos a ningún servidor." },
    { section: "Análisis (JSON)",       selector: '[data-tut="config-json"]',
      title: "Tu base de conocimiento",
      text: "El panel derecho. Sube el analysis.json con las tesis, rangos y estimaciones por ticker. Este archivo alimenta Candidates, Análisis, Movimientos y el retorno esperado del header." },
    { section: "Plantillas",            selector: '[data-tut="config-csv"]',
      title: "Descarga los formatos base",
      text: "Los botones 'Descargar plantilla' de cada panel guardan directamente en la carpeta Templates/ de STOX el CSV o JSON vacío con la estructura exacta que espera la aplicación." },
  ],
};

export const I18N = {
  es: {
    modeDemo: "MODO DEMO — sube tu CSV en ⚙ Configuración",
    invested: "Invertido",
    target: "Objetivo",
    tabProyecto: "Inicio",
    tabEvolucion: "Evolución",
    tabPortfolio: "Mi portfolio",
    tabCandidates: "Candidates",
    tabAnalisis: "Análisis",
    tabVolatilidad: "Volatilidad",
    tabConfig: "⚙ Configuración",
    demoBanner: "Datos de ejemplo. Ve a",
    demoConfig: "Configuración",
    demoSuffix: "para actualizar el estado de tu proyecto.",
    goToConfig: "Ir a Configuración →",
    cardPortfolio: "Portfolio",
    cardCapital: "Capital desplegado",
    cardRealCapital: "Capital real desplegado",
    cardPositions: "Posiciones",
    cardPotReturn: "Retorno potencial",
    cardPotReturnSub: "Media ponderada sobre capital",
    cardExpected: "Valor esperado",
    noPotData: "Sin datos de potencial en el análisis",
    loadCsvConfig: "Carga tu CSV en Configuración para ver la distribución real de tu cartera.",
    loadAnalysisConfig: "Carga tu analysis.json en ⚙ Configuración",
    proyectoTitle: "Configuración del proyecto",
    proyectoDesc: "Define tu estrategia de inversión, distribución por bucket y objetivos.",
    investMode: "Modo de inversión",
    modeOnce: "Inversión puntual",
    modeOnceSub: "Un único desembolso de capital",
    modePeriodic: "Inversión periódica",
    modePeriodicSub: "Aportaciones regulares programadas",
    periodicity: "Periodicidad",
    monthly: "Mensual",
    quarterly: "Trimestral",
    monthlyAmount: "Aportación mensual",
    quarterlyAmount: "Aportación trimestral",
    annualPlanned: "Inversión anual planeada",
    targetAmount: "Importe a invertir",
    targetAmountDesc: "Capital total disponible para esta inversión",
    presets: "Distribución por bucket",
    conservative: "Conservador",
    balanced: "Equilibrado",
    aggressive: "Agresivo",
    coreAlloc: "Core · ETFs / Dividendos estables",
    satelliteAlloc: "Satellite · Crecimiento selectivo",
    wildshotsAlloc: "Wildshots · Alta convicción / alto riesgo",
    evolucionTitle: "Evolución del portfolio",
    currentInvest: "Inversión actual",
    objective: "Objetivo",
    remaining: "Faltan",
    completed: "completado",
    projectedGrowth: "Crecimiento proyectado",
    potReturn: "Retorno potencial",
    potReturnPct: "Retorno potencial (%)",
    distTitle: "Distribución real vs objetivo",
    real: "Real",
    bucketBreakdown: "Desglose por bucket",
    capital: "Capital (€)",
    distribution: "Distribución (%)",
    progress: "Progreso",
    retPotential: "Ret. potencial",
    rrWeighted: "R/R ponderado",
    inObjective: "✓ En objetivo",
    vsObjective: "pp vs objetivo",
    nextMoveSub_once: "despliegue del capital total",
    nextMoveSub_monthly: "compra sugerida este mes",
    buyNow: "Invertir ahora",
    buyThisMonth: "Comprar este mes",
    buyThisQuarter: "Comprar este trimestre",
    closePlan: "Cerrar plan ▲",
    openPlanOnce: "Ver plan de despliegue ▼",
    openPlan: "Ver plan completo ▼",
    planTotal: "Plan de despliegue total",
    planQuarterly: "Plan trimestral — saldo restante",
    planMonthly: "Plan mensual completo",
    budgetExhausted: " · presupuesto agotado este trimestre",
    deployed: "desplegados",
    surplus: "restantes",
    accumulate: "Acumular",
    accumulateNext_monthly: "mes que viene",
    accumulateNext_quarterly: "próximo trimestre",
    accumulatePrefix: "Acumular el",
    accumulateSuffix: "(no llegan a",
    accumulateInsuf: "Importe insuficiente (mínimo",
    candidatesTitle: "Investment Candidates",
    candidatesDesc: "Universo de candidatos por bucket. Haz clic para ver thesis, catalizadores y escenarios.",
    noCandidates: "Sin candidatos cargados",
    noCandidatesDesc: "Carga tu analysis.json en Configuración para ver los candidatos, tesis y sugerencias de compra.",
    rrRatio: "R/R ratio",
    riskTitle: "Análisis de riesgos",
    riskDesc: "Vulnerabilidades del portfolio y estimaciones de bajada por posición.",
    noAnalysisData: "Sin datos de análisis",
    noAnalysisDesc: "Carga tu analysis.json con los campos rango y estimacion en Configuración.",
    maxLoss: "Pérdida máxima estimada",
    maxLossScenario: "Escenario adverso",
    positionsCovered: "posiciones cubiertas",
    candWithRisk: "Candidates con datos de riesgo",
    candWithRiskDesc: "Del universo de candidatos analizados",
    currentPortfolio: "Portfolio actual",
    positions: "posiciones",
    position: "posición",
    candidates_label: "Candidates",
    analyzed: "analizados",
    ticker: "Ticker",
    name: "Nombre",
    maxDown: "Bajada máx.",
    maxUp: "Subida máx.",
    bearScenarios: "Escenarios bajistas",
    analysisTitle: "Análisis de empresas",
    analysisDesc: "Descripción del negocio, ventaja competitiva y motivo de inversión por candidato. Haz clic en una empresa para leer su análisis.",
    noAnalysis: "Sin análisis cargado",
    noAnalysisSubDesc: "Carga tu analysis.json en Configuración para ver las tesis, candidatos y escenarios por empresa.",
    analyzed_label: "analizados",
    pending: "pendientes",
    thesis: "Tesis",
    advantage: "Ventaja competitiva",
    whyNow: "¿Por qué ahora?",
    mainRisk: "Riesgo principal",
    consensus: "Consenso",
    bearScenario: "Escenario bajista",
    bullScenario: "Escenario alcista",
    configTitle: "Configuración",
    configDesc: "Importa tus datos de eToro y el análisis de empresas. Todo se procesa localmente en tu navegador.",
    positionsData: "Datos de posiciones",
    csvLoaded: "CSV cargado",
    dragCsv: "Arrastra tu CSV aquí",
    clickSelect: "o haz clic para seleccionar",
    expectedCols: "Columnas esperadas",
    hideCsvTemplate: "Ocultar plantilla",
    showCsvTemplate: "Ver plantilla CSV",
    analysisData: "Datos de análisis",
    dragJson: "Arrastra tu analysis.json aquí",
    analysisLoaded: "Analysis cargado",
    claudeAnalysisTitle: "Análisis geopolítico con Claude",
    claudeAnalysisDesc: "Abre un nuevo chat de Claude con el análisis completo pre-configurado. La fecha de hoy y tu portfolio actual se rellenan automáticamente.",
    eventoLabel: "Evento geopolítico a analizar",
    eventoPlaceholder: "Ej: \"Aranceles de Trump a la UE\", \"Crisis en Taiwán\"",
    sectoresLabel: "Sectores nuevos a explorar",
    sectoresPlaceholder: "Ej: \"Defensa, Energía\" o \"Déjalo en tu criterio\"",
    dateAuto: "Fecha (auto)",
    portfolioAuto: "Portfolio (auto",
    openClaude: "Abrir análisis en Claude →",
    deepResearchNote: "Activa Deep Research manualmente en el chat antes de enviar para mejores resultados",
    noFinancialAdvice: "No es asesoramiento financiero · Referencia personal",
    processing: "Procesando...",
    error: "Error",
    copy: "Copiar",
    positions_label: "posiciones",
  },
  en: {
    modeDemo: "DEMO MODE — upload your CSV in ⚙ Settings",
    invested: "Invested",
    target: "Target",
    tabProyecto: "Home",
    tabEvolucion: "Evolution",
    tabPortfolio: "My Portfolio",
    tabCandidates: "Candidates",
    tabAnalisis: "Analysis",
    tabVolatilidad: "Volatility",
    tabConfig: "⚙ Settings",
    demoBanner: "Sample data. Go to",
    demoConfig: "Settings",
    demoSuffix: "to update your project status.",
    goToConfig: "Go to Settings →",
    cardPortfolio: "Portfolio",
    cardCapital: "Deployed capital",
    cardRealCapital: "Real deployed capital",
    cardPositions: "Positions",
    cardPotReturn: "Potential return",
    cardPotReturnSub: "Weighted avg over capital",
    cardExpected: "Expected value",
    noPotData: "No potential data in analysis",
    loadCsvConfig: "Load your CSV in Settings to see your portfolio distribution.",
    loadAnalysisConfig: "Load your analysis.json in ⚙ Settings",
    proyectoTitle: "Project setup",
    proyectoDesc: "Define your investment strategy, bucket allocation and targets.",
    investMode: "Investment mode",
    modeOnce: "One-time investment",
    modeOnceSub: "Single capital deployment",
    modePeriodic: "Periodic investment",
    modePeriodicSub: "Regular scheduled contributions",
    periodicity: "Frequency",
    monthly: "Monthly",
    quarterly: "Quarterly",
    monthlyAmount: "Monthly contribution",
    quarterlyAmount: "Quarterly contribution",
    annualPlanned: "Planned annual investment",
    targetAmount: "Amount to invest",
    targetAmountDesc: "Total capital available for this investment",
    presets: "Bucket allocation",
    conservative: "Conservative",
    balanced: "Balanced",
    aggressive: "Aggressive",
    coreAlloc: "Core · ETFs / Stable dividends",
    satelliteAlloc: "Satellite · Selective growth",
    wildshotsAlloc: "Wildshots · High conviction / high risk",
    evolucionTitle: "Portfolio evolution",
    currentInvest: "Current investment",
    objective: "Target",
    remaining: "Remaining",
    completed: "completed",
    projectedGrowth: "Projected growth",
    potReturn: "Potential return",
    potReturnPct: "Potential return (%)",
    distTitle: "Actual vs target distribution",
    real: "Actual",
    bucketBreakdown: "Bucket breakdown",
    capital: "Capital (€)",
    distribution: "Distribution (%)",
    progress: "Progress",
    retPotential: "Pot. return",
    rrWeighted: "Weighted R/R",
    inObjective: "✓ On target",
    vsObjective: "pp vs target",
    nextMoveSub_once: "total capital deployment",
    nextMoveSub_monthly: "suggested buy this month",
    buyNow: "Invest now",
    buyThisMonth: "Buy this month",
    buyThisQuarter: "Buy this quarter",
    closePlan: "Close plan ▲",
    openPlanOnce: "View deployment plan ▼",
    openPlan: "View full plan ▼",
    planTotal: "Total deployment plan",
    planQuarterly: "Quarterly plan — remaining budget",
    planMonthly: "Full monthly plan",
    budgetExhausted: " · quarterly budget exhausted",
    deployed: "deployed",
    surplus: "remaining",
    accumulate: "Accumulate",
    accumulateNext_monthly: "next month",
    accumulateNext_quarterly: "next quarter",
    accumulatePrefix: "Accumulate",
    accumulateSuffix: "(below",
    accumulateInsuf: "Insufficient amount (min",
    candidatesTitle: "Investment Candidates",
    candidatesDesc: "Candidate universe by bucket. Click to see thesis, catalysts and scenarios.",
    noCandidates: "No candidates loaded",
    noCandidatesDesc: "Load your analysis.json in Settings to see candidates, thesis and buy suggestions.",
    rrRatio: "R/R ratio",
    riskTitle: "Risk analysis",
    riskDesc: "Portfolio vulnerabilities and downside estimates by position.",
    noAnalysisData: "No analysis data",
    noAnalysisDesc: "Load your analysis.json with rango and estimacion fields in Settings.",
    maxLoss: "Estimated max loss",
    maxLossScenario: "Adverse scenario",
    positionsCovered: "positions covered",
    candWithRisk: "Candidates with risk data",
    candWithRiskDesc: "From the analyzed candidate universe",
    currentPortfolio: "Current portfolio",
    positions: "positions",
    position: "position",
    candidates_label: "Candidates",
    analyzed: "analyzed",
    ticker: "Ticker",
    name: "Name",
    maxDown: "Max. drawdown",
    maxUp: "Max. upside",
    bearScenarios: "Bear scenarios",
    analysisTitle: "Company analysis",
    analysisDesc: "Business description, competitive advantage and investment rationale per candidate. Click a company to read its analysis.",
    noAnalysis: "No analysis loaded",
    noAnalysisSubDesc: "Load your analysis.json in Settings to see thesis, candidates and scenarios per company.",
    analyzed_label: "analyzed",
    pending: "pending",
    thesis: "Thesis",
    advantage: "Competitive advantage",
    whyNow: "Why now?",
    mainRisk: "Main risk",
    consensus: "Consensus",
    bearScenario: "Bear scenario",
    bullScenario: "Bull scenario",
    configTitle: "Settings",
    configDesc: "Import your eToro data and company analysis. Everything is processed locally in your browser.",
    positionsData: "Positions data",
    csvLoaded: "CSV loaded",
    dragCsv: "Drag your CSV here",
    clickSelect: "or click to select",
    expectedCols: "Expected columns",
    hideCsvTemplate: "Hide template",
    showCsvTemplate: "View CSV template",
    analysisData: "Analysis data",
    dragJson: "Drag your analysis.json here",
    analysisLoaded: "Analysis loaded",
    claudeAnalysisTitle: "Geopolitical analysis with Claude",
    claudeAnalysisDesc: "Opens a new Claude chat with the full analysis pre-configured. Today's date and your current portfolio are filled in automatically.",
    eventoLabel: "Geopolitical event to analyze",
    eventoPlaceholder: "E.g. \"Trump tariffs on the EU\", \"Taiwan crisis\"",
    sectoresLabel: "New sectors to explore",
    sectoresPlaceholder: "E.g. \"Defense, Energy\" or \"Leave it to your discretion\"",
    dateAuto: "Date (auto)",
    portfolioAuto: "Portfolio (auto",
    openClaude: "Open analysis in Claude →",
    deepResearchNote: "Enable Deep Research manually in the chat before sending for best results",
    noFinancialAdvice: "Not financial advice · Personal reference",
    processing: "Processing...",
    error: "Error",
    copy: "Copy",
    positions_label: "positions",
  }
};
